version: '2'

services:
  db:
    image: postgres:11.3
    ports:
      - 5432:5432
    volumes:
      - ./tools/db_init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=librarychecker
      - POSTGRES_PASSWORD=passwd
    healthcheck:
        test: [ "CMD", "pg_isready", "-q", "-d", "librarychecker", "-U", "postgres" ]
        timeout: 10s
        interval: 1s
        retries: 30

  minio:
    image: minio/minio
    command: server /data --console-address :9001
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=miniopass
  create-minio-bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minio miniopass;
      /usr/bin/mc rm --recursive --force myminio/testcase;
      /usr/bin/mc mb myminio/testcase;
      /usr/bin/mc policy download myminio/testcase;
      exit 0;
      "

  api:
    build:
      dockerfile: Dockerfile.API
    command: -pghost=db -hmackey=dummy_secret
    ports:
      - 50051:50051
    depends_on:
      db:
        condition: service_healthy
      create-minio-bucket:
        condition: service_completed_successfully
    environment:
      - API_DB_LOG=true
    healthcheck:
        test: grpc_health_probe -addr localhost:50051
        timeout: 10s
        interval: 1s
        retries: 30

  api-grpcweb:
    build:
      dockerfile: Dockerfile.API
    command: -grpcweb -pghost=db -hmackey=dummy_secret
    ports:
      - 58080:50051
    depends_on:
      db:
        condition: service_healthy
      create-minio-bucket:
        condition: service_completed_successfully
    environment:
      - API_DB_LOG=true
    healthcheck:
        test: wget -q -O - localhost:50051/health || exit 1
        timeout: 10s
        interval: 1s
        retries: 30
