version: '2'

services:
  db:
    image: postgres:11.3
    ports:
      - 5432:5432
    volumes:
      - ./tools/db_init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=librarychecker
      - POSTGRES_PASSWORD=passwd
    healthcheck:
        test: [ "CMD", "pg_isready", "-q", "-d", "librarychecker", "-U", "postgres" ]
        timeout: 45s
        interval: 10s
        retries: 10

  minio:
    image: minio/minio
    command: server /data
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=miniopass

  api:
    build:
      context: api
    ports:
      - 50051:50051
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRE_HOST=db
      - HMAC_SECRET=dummy_secret
      - API_DB_LOG=true

  api-grpcweb:
    build:
      context: api
    ports:
      - 58080:50051
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRE_HOST=db
      - HMAC_SECRET=dummy_secret
      - API_DB_LOG=true
      - MODE=gRPCWeb
