version: '2'

services:
  db:
    image: postgres:11.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=librarychecker
      - POSTGRES_PASSWORD=passwd
  api:
    build:
      context: api
    ports:
      - 50051:50051
    depends_on:
      - db
    environment:
      - POSTGRE_HOST=db
      - HMAC_SECRET=dummy_secret