#cloud-config

# Ubuntu 18.04

timezone: Asia/Tokyo
locale: ja_JP.utf8

runcmd:
  # install AC Library
  - curl https://img.atcoder.jp/practice2/ac-library.zip --output ac-library.zip
  - unzip ac-library.zip -d ac-library
  - cp -r ac-library /opt/
  - touch /root/can_start

