#cloud-config

# Ubuntu 18.04

timezone: Asia/Tokyo
locale: ja_JP.utf8

users:
  - name: library-checker-user
    uid: 2000

packages:
  - cgroup-tools
  - supervisor
  - postgresql-client
  - libpq-dev
  - libcap2-bin
  - unzip
  # compilers
  - g++
  - default-jdk
  - default-jre
  - python3
  - python3-dev
  - python3-pip
  - python3.7
  - python3.7-dev
  - rustc
  - ghc
  
write_files:
  - path: /etc/default/grub.d/99-lib-judge.cfg
    owner: root:root
    content: GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX_DEFAULT swapaccount=1"

  - path: /etc/supervisor/conf.d/judge.conf
    owner: root:root
    permissions: '0600'
    content: |
      [program:judge]
      command=/root/library-checker-judge/judge/judge
      autorestart=true
      stdout_logfile=/root/judge.log
      stderr_logfile=/root/judge-err.log
      user=root
      directory=/root/library-checker-judge/judge/
      startsecs=10
      startretries=300

  - path: /var/lib/cloud/scripts/per-boot/judge-launch.sh
    owner: root:root
    permissions: '0755'
    content: |
      #!/bin/bash
      if [[ -f /root/init_end ]]; then
        echo "Second Time"
        touch /root/can_start
      else
        echo "First Time"
        touch /root/init_end
        if [[ -f /root/library-checker-judge/judge/judge ]]; then
          supervisorctl start judge
        fi
      fi

runcmd:
  - update-grub
  # install docker, docker-compose
  - curl -fsSL https://get.docker.com -o get-docker.sh; sh get-docker.sh
  - curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose

  - git clone https://github.com/yosupo06/library-checker-problems /root/library-checker-problems
  - pip3 install termcolor toml psycopg2 psutil
  - pip3 install -r /root/library-checker-problems/requirements.txt
  # install go
  - add-apt-repository -y ppa:longsleep/golang-backports
  - apt-get install -y golang-go
  # install numpy, scipy
  - python3.7 -m pip install --upgrade numpy scipy

power_state:
  mode: reboot
  timeout: 15
