steps:
  - name:	gcr.io/cloud-builders/gcloud
    entrypoint: sh
    dir: deploy
    args: ./deploy.sh
    env:
      - 'PG_HOST=$_PG_HOST'
      - 'PG_PASS=$_PG_PASS'
      - 'CREATE_OPTION=$_CREATE_OPTION'

timeout: 1800s
