steps:
  - name:	gcr.io/cloud-builders/gcloud
    entrypoint: bash
    dir: deploy
    args: [./deploy.sh]
    env:
      - 'PG_HOST=$_PG_HOST'
      - 'PG_PASS=$_PG_PASS'
      - 'API_PASS=$_API_PASS'
      - 'MINIO_HOST=$_MINIO_HOST'
      - 'MINIO_ACCESS=$_MINIO_ACCESS'
      - 'MINIO_SECRET=$_MINIO_SECRET'
      - 'MINIO_BUCKET=$_MINIO_BUCKET'
      - 'CREATE_OPTION=$_CREATE_OPTION'

timeout: 1800s
