[langs.checker]
    source = "checker.cpp"
    compile = "g++ -O2 -std=c++14 -march=native -o checker checker.cpp"
[langs.cpp]
    source = "main.cpp"
    compile = "g++ -O2 -std=c++17 -march=native -o main main.cpp"
    exec = "./main"
[langs.cpp14]
    source = "main.cpp"
    compile = "g++ -O2 -std=c++14 -march=native -o main main.cpp"
    exec = "./main"
[langs.rust]
    source = "main.rs"
    compile = "rustc -O main.rs"
    exec = "./main"
[langs.d]
    source = "main.d"
    compile = "ldc2 -O -release main.d"
    exec = "./main"
[langs.java]
    source = "Main.java"
    compile = "javac Main.java"
    exec = "java -Xss1G Main"
[langs.pypy3]
    source = "main.py"
    compile = "pypy3 -c 'print(1)'"
    exec = "pypy3 main.py"
[langs.haskell]
    source = "main.hs"
    compile = "ghc -O2 main.hs"
    exec = "./main"
