[langs.checker]
    source = "checker.cpp"
    compile = "g++ -O2 -std=c++14 -march=native -o checker checker.cpp"
    exec = "./checker {input} {contestant} {judge}"
[langs.cpp]
    source = "main.cpp"
    compile = "g++ -O2 -std=c++17 -march=native -o main main.cpp"
    exec = "./main"
[langs.cpp14]
    source = "main.cpp"
    compile = "g++ -O2 -std=c++14 -march=native -o main main.cpp"
    exec = "./main"
[langs.rust]
    source = "main.rs"
    compile = "rustc -O main.rs"
    exec = "./main"
[langs.d]
    source = "main.d"
    compile = "ldc2 -O -release main.d"
    exec = "./main"
[langs.java]
    source = "Main.java"
    compile = "javac Main.java"
    exec = "java -Xss1G Main"
[langs.pypy3]
    source = "Main.py"
    compile = "echo dummy"
    exec = "pypy3 Main.py"
