name: API-Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: ./gen_protoc.sh

    - id: run-docker-compose
      name: Run docker compose
      run: docker compose up -d --build --wait

    - name: Uploader module test
      run: go test .
      working-directory: ./uploader

    - name: Database module test
      run: go test .
      working-directory: ./database

    - name: Storage module test
      run: go test .
      working-directory: ./storage

    - name: Api module test
      run: go test .
      working-directory: ./api

    - name: Uploader module test
      run: go test .
      working-directory: ./uploader
