name: Deploy

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      problems-branch:
        type: string
        default: master
      build-base:
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      env:
        type: string
        default: dev
        description: Environment of deploy
      problems-branch:
        type: string
        default: master
        description: Branch of library-checker-problems
      build-base:
        type: boolean
        default: true
        description: Build a base image of judge or not

env:
  TF_CLOUD_ORGANIZATION: "yosupo06-org"
  TF_WORKSPACE: "${{ inputs.env }}-library-checker"

jobs:
  db-migrate:
    uses: ./.github/workflows/db-migrate.yml
    secrets: inherit
    with:
      env: ${{ inputs.env }}

  api-deploy:
    needs: db-migrate
    uses: ./.github/workflows/api-deploy.yml
    secrets: inherit
    with:
      env: ${{ inputs.env }}

  problems-deploy:
    needs: api-deploy
    uses: ./.github/workflows/problems-deploy.yml
    secrets: inherit
    with:
      env: ${{ inputs.env }}
      problems-branch: ${{ inputs.problems-branch }}

  judge-deploy:
    needs: problems-deploy
    uses: ./.github/workflows/judge-image-build.yml
    secrets: inherit
    with:
      env: ${{ inputs.env }}
      build-base: ${{ inputs.build-base }}

  terraform-apply:
    needs: judge-deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform init
        working-directory: ./terraform
      - run: terraform apply --auto-approve
        working-directory: ./terraform
