name: Deploy

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      env:
        default: dev
        type: string
        description: environment of deploy

jobs:
  api-deploy:
    uses: ./.github/workflows/api-deploy.yml
    with:
      env: ${{ inputs.env }}

  problems-deploy:
    needs: api-deploy
    uses: ./.github/workflows/problems-deploy.yml
    with:
      env: ${{ inputs.env }}

  judge-deploy:
    needs: problems-deploy
    uses: ./.github/workflows/judge-deploy.yml
    with:
      env: ${{ inputs.env }}
