name: Dev-Problems-Deploy

on:
  workflow_dispatch:
    inputs:
      force:
        type: boolean
        default: false
        description: "force upload"

jobs:
  problems-deploy:
    uses: ./.github/workflows/problems-deploy.yml
    secrets: inherit
    with:
      env: dev
      force: ${{ inputs.force }}
