name: Judge-Test-GCE

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  judge-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: projects/190778459730/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
        service_account: gce-judge-deployer@library-checker-project.iam.gserviceaccount.com
        token_format: access_token
    
    - id: setup-cloud-sdk
      name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - id: test-on-gce
      name:	Run test_on_gce.py
      run: ./test_on_gce.py --zone asia-northeast1-a --env prod
      working-directory: ./deploy
