name: Judge-Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  judge-test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    
    - id: build-lang-images
      name: Build lang images
      run: ./build.sh
      working-directory: ./langs

    - run: ./gen_protoc.sh

    - id: test-judge
      name: Test judge
      run: go test -v .
      working-directory: ./judge

