name: Judge-Deploy

on:
  workflow_dispatch:
    inputs:
      zone:
        description: 'Instance zone'
        required: true
        default: asia-northeast1-a
        type: string
      build_image:
        description: 'Build new judge image'
        required: true
        default: false
        type: boolean

jobs:
  judge-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: projects/190778459730/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
        service_account: gce-judge-deployer@library-checker-project.iam.gserviceaccount.com
        token_format: access_token
    
    - id: build-image
      name: Build judge image
      if : ${{ inputs.build_image }}
      run: packer build -var 'env=prod' .
      working-directory: ./packer

    - id: setup-cloud-sdk
      name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - id: judge-deploy
      name:	Run judge-deploy.py
      run: ./judge_deploy.py --zone $ZONE --env prod --preemptible
      working-directory: ./deploy
      env:
        ZONE: ${{ inputs.zone }}