name: Judge Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Setup gcloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GCLOUD_EMAIL }}
        service_account_key: ${{ secrets.GCLOUD_KEY }}
    
    - name: Clone problems
      run: |
        git clone https://github.com/yosupo06/library-checker-problems/

    - name: Print ID Test
      run: |
        cat /dev/urandom | LC_CTYPE=C tr -d -c '[:lower:]' | fold -w 10 | head -n 1
        
    - name: Run test
      run: |
        cd test && ./gce_test.sh
    