name: Problems-Deploy

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

concurrency:
  group: ${{ inputs.env }}-problems-deploy
  cancel-in-progress: true

jobs:
  problems-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: yosupo06/library-checker-problems
        path: library-checker-problems

    - id: auth
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: projects/190778459730/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
        service_account: cloud-run-deployer@library-checker-project.iam.gserviceaccount.com
        token_format: access_token
    
    - uses: docker/login-action@v1
      with:
        registry: asia-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - id: gen-protoc
      name: Generate protoc
      run: ./api/gen_protoc.sh

    - id: build-docker
      name: Build docker image
      run: docker build -t asia-docker.pkg.dev/library-checker-project/${{ inputs.env }}-docker-repo/uploader -f Dockerfile.UPLOADER .

    - id: push-docker
      name: Push docker image
      run: docker push asia-docker.pkg.dev/library-checker-project/${{ inputs.env }}-docker-repo/uploader

    # TODO: migrate to google-github-actions/deploy-cloudrun@v0
    - id: setup-cloud-sdk
      name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        install_components: beta

    - id: deploy-problems
      name: Deploy Problems
      run: >
        gcloud beta run jobs deploy ${{ inputs.env }}-upload
        --execute-now
        --wait
        --region=asia-northeast1
        --image=asia-docker.pkg.dev/library-checker-project/${{ inputs.env }}-docker-repo/uploader
        --cpu=4
        --memory=16Gi
        --tasks=100
        --parallelism=100
        --max-retries=0
        --set-cloudsql-instances=library-checker-sql
        --set-secrets=API_PASS=api-judge-pass:latest,MINIO_HOST=minio-host:latest,MINIO_ID=minio-id:latest,MINIO_SECRET=minio-secret:latest,MINIO_BUCKET=minio-bucket:latest
        --service-account=problems-deployer@library-checker-project.iam.gserviceaccount.com
        --quiet
