name: Prod-Problems-Deploy

on:
  repository_dispatch:
  push:
    branches:
      - master
      - test/ci2

jobs:
  problems-deploy:
    uses: ./.github/workflows/problems-deploy.yml
    secrets: inherit
    with:
      env: prod
