name: Prod-Deploy

on:
  push:
    branches: 
      - master

jobs:
  api-deploy:
    uses: ./.github/workflows/api-deploy.yml
    with:
      env: prod

  problems-deploy:
    needs: api-deploy
    uses: ./.github/workflows/prod-problems-deploy.yml

  judge-deploy:
    needs: problems-deploy
    uses: ./.github/workflows/judge-deploy.yml
    with:
      env: prod
